### ISSUE TITLE
Trailing commas

### ISSUE THREAD

**Issue by eliperelman** [mozilla-rpweb/discussions#2]
I've tried and tried, and I just can't seem to get used to putting trailing commas in arrays and objects.

```js
[
  a,
  b,
  c,
]

{
  a,
  b,
  c,
}
```

I'd like to get some more opinions on trailing commas, and if we feel that the majority here favor or oppose them. Any changes we decide to deviate from neutrino presets should go into a new rp-web preset. For context:

https://sqren.github.io/eslint-compare/

`comma-dangle` (which throws on missing comma) is an error in the AirBnB preset, which is what the neutrino presets are based on. eslint-recommended allows leaving off the comma, and StandardJS throws if it's preset, while Google requires it.

**Comment by darkwing** [comment]
It's weird to me but I'm fin with keeping it; I just do what eslint tells me :D

**Comment by helfi92** [comment]
The only benefit I can see from that is cleaner diffs. Otherwise, it makes my eyes bleed.

**Comment by eliperelman** [comment]
I especially find it strange inside objects. When using a ternary or function as a value, it feels weird when it's all alone:

```js
this.setState({
  item: a === 'c' ?
    a.value :
    b.value,
});
```

```js
this.setState({
  item: items.find(i => i.id === id),
});
```

**Comment by eliperelman** [comment]
cc: @camd @purelogiq would appreciate your opinions if you have them.

**Comment by camd** [comment]
I've heard the argument that it makes it easier when rearranging items in a list.  Especially moving the last item up in the order.  Or adding new ones with a copy/paste.  So, I kinda like it myself.  That being said, I don't have a very strong opinion on it.  :)  As @darkwing said, as long as my linter is happy, I'm happy.  Oh, and as long as Eli is happy.  Cause of that time he said, "Don't make me angry.  You wouldn't like me when I'm angry."

**Comment by purelogiq** [comment]
If I were coding in my own personal space, I would go without them. 
But, if there is a benefit to having them when working on a team then sure :)
![neutral pic](http://s2.quickmeme.com/img/18/18b79f39511f6ae7a40a414de74c5d7d146d9f21e5e36ac7c5e8117b17c6decf.jpg)

**Comment by eliperelman** [comment]
Sounds like the majority votes for no trailing commas. This is now in place in the rpweb neutrino preset.
