### ISSUE TITLE
Using `this` in each component method

### ISSUE THREAD

**Issue by darkwing** [mozilla-rpweb/discussions#3]
So I've been using `getInitialProps` to help manage state, but I get the usual `Expected 'this' to be used by class method 'getInitialProps'  class-methods-use-this` error.  Seems weird to have `getInitialProps` be a function outside of the class.

What do you guys do here?

**Comment by eliperelman** [comment]
In [TaskCluster's neutrino web preset ESLint rules](https://github.com/taskcluster/neutrino-preset-taskcluster-web/blob/master/src/eslint.js), we specifically shut off `class-methods-use-this`:

```js
// Allow using class methods with static/non-instance functionality
// React lifecycle methods commonly do not use an instance context for anything
'class-methods-use-this': 'off',
```

Like you're seeing, React requires some lifecycle methods, which may not use the class's context, making ESLint cry. Maybe we should port the TaskCluster web preset to be our rpweb baseline preset.

**Comment by purelogiq** [comment]
I also have encountered this headache, and have valid cases for not using `this` in a class method.

**Comment by eliperelman** [comment]
This has been resolved in the new rpweb neutrino preset.
